// USER
export const SET_USER = 'SET_USER'
export const UNSET_USER = 'UNSET_USER'
// MEDIA
export const SET_MY_MEDIAS = 'SET_MY_MEDIAS'
export const SET_REWATCH_MEDIAS = 'SET_REWATCH_MEDIAS'
export const ADD_TO_LIST = 'ADD_TO_LIST'
export const REMOVE_FROM_LIST = 'REMOVE_FROM_LIST'
export const SELECT_MEDIA = 'SELECT_MEDIA'
export const UNSELECT_MEDIA = 'UNSELECT_MEDIA'
export const SET_WATCHED = 'SET_WATCHED'
export const UNSET_WATCHED = 'UNSET_WATCHED'
// MEDIA SEARCH
export const SET_SEARCHED_MEDIAS = 'SET_SEARCHED_MEDIAS'
export const CLEAR_SEARCHED_MEDIAS = 'CLEAR_SEARCHED_MEDIAS'
export const DEFINE_SUGGESTIONS = 'DEFINE_SUGGESTIONS'
